"use client"

import { ColumnDef } from "@tanstack/react-table"
import { ArrowUpDownIcon, DownloadIcon } from "lucide-react"
import { useState } from "react"
import { toast } from "sonner"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { downloadStoredReportAction } from "@/lib/actions"
import { triggerBrowserDownload } from "@/lib/download-utils"
import { formatStockTimestamp } from "@/lib/stock-utils"
import type { StoredReport } from "@/types/app.types"

function formatBadgeVariant(format: string) {
  if (format === "PDF") return "default" as const
  if (format === "EXCEL") return "secondary" as const
  return "outline" as const
}

export const storedReportColumns: ColumnDef<StoredReport>[] = [
  {
    accessorKey: "name",
    header: ({ column }) => (
      <Button
        variant="ghost"
        className="px-0 hover:bg-transparent"
        onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
      >
        Report Name
        <ArrowUpDownIcon className="ml-2 size-4" />
      </Button>
    ),
    cell: ({ row }) => (
      <p className="font-medium">{row.getValue("name")}</p>
    ),
  },
  {
    accessorKey: "format",
    header: "Format",
    cell: ({ row }) => {
      const format = row.getValue("format") as string
      return <Badge variant={formatBadgeVariant(format)}>{format}</Badge>
    },
  },
  {
    accessorKey: "generatedBy",
    header: "Generated By",
    cell: ({ row }) => (
      <span className="text-muted-foreground">{row.getValue("generatedBy")}</span>
    ),
  },
  {
    accessorKey: "generatedAt",
    header: ({ column }) => (
      <Button
        variant="ghost"
        className="px-0 hover:bg-transparent"
        onClick={() => column.toggleSorting(column.getIsSorted() === "asc")}
      >
        Generated At
        <ArrowUpDownIcon className="ml-2 size-4" />
      </Button>
    ),
    cell: ({ row }) => (
      <span className="text-muted-foreground">
        {formatStockTimestamp(row.getValue("generatedAt"))}
      </span>
    ),
  },
  {
    id: "actions",
    cell: ({ row }) => <DownloadReportButton report={row.original} />,
    enableSorting: false,
  },
]

function DownloadReportButton({ report }: { report: StoredReport }) {
  const [loading, setLoading] = useState(false)

  async function handleDownload() {
    setLoading(true)
    try {
      const result = await downloadStoredReportAction(report.id)

      if (!result.ok) {
        toast.error("Download failed", { description: result.message })
        return
      }

      triggerBrowserDownload(result.data, result.contentType, result.filename)
      toast.success("Report downloaded")
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="flex justify-end">
      <Button
        type="button"
        variant="outline"
        size="sm"
        disabled={loading}
        onClick={handleDownload}
        data-testid="download-report-button"
      >
        <DownloadIcon className="mr-2 size-4" />
        {loading ? "Downloading..." : "Download"}
      </Button>
    </div>
  )
}
